#!/usr/bin/env bash
set -euo pipefail

OPENAPI_FILE="rules/unified-api.openapi.yaml"
HUMAN_FILE="rules/unified-api.human.md"

if [[ ! -f "$OPENAPI_FILE" ]]; then
  echo "Missing file: $OPENAPI_FILE" >&2
  exit 1
fi

tmp_file="$(mktemp)"

extract_block() {
  local start_pattern="$1"
  local end_pattern="$2"
  awk -v start="$start_pattern" -v end="$end_pattern" '
    $0 ~ start { flag=1 }
    flag && $0 ~ end { flag=0; next }
    flag { print }
  ' "$OPENAPI_FILE"
}

extract_to_eof() {
  local start_pattern="$1"
  awk -v start="$start_pattern" '
    $0 ~ start { flag=1 }
    flag { print }
  ' "$OPENAPI_FILE"
}

supported_languages="$(awk -F'[][]' '/supportedLanguages:/ {print $2; exit}' "$OPENAPI_FILE" | sed 's/,/, /g' | tr -d "'")"
default_language="$(sed -n 's/.*service default (\(.*\)).*/\1/p' "$OPENAPI_FILE" | head -n 1)"

{
  echo "# Unified API Rules (Human Readable)"
  echo
  echo "> Auto-generated from \`$OPENAPI_FILE\` by \`scripts/sync-api-docs.sh\`."
  echo "> Do not edit this file manually."
  echo
  echo "## Canonical Source"
  echo
  echo "- Machine source of truth: \`$OPENAPI_FILE\`"
  echo "- Human doc (generated): \`$HUMAN_FILE\`"
  echo
  echo "## Quick Summary"
  echo
  echo "- Default language: \`$default_language\`"
  echo "- Supported languages: \`$supported_languages\`"
  echo "- Response envelope: \`ApiResponse\` / \`ApiErrorResponse\`"
  echo "- Pagination: \`PageResult\` and \`CursorResult\`"
  echo
  echo "## API Design Conventions (from x-rules.apiDesign)"
  echo
  echo '```yaml'
  extract_block '^  apiDesign:' '^  i18n:'
  echo '```'
  echo
  echo "## Language Rules (from x-rules.i18n)"
  echo
  echo '```yaml'
  extract_block '^  i18n:' '^  pagination:'
  echo '```'
  echo
  echo "## HTTP Status Policy (from x-rules.httpStatusPolicy)"
  echo
  echo '```yaml'
  extract_block '^  httpStatusPolicy:' '^  documentation:'
  echo '```'
  echo
  echo "## Response Envelope (ApiResponse)"
  echo
  echo '```yaml'
  extract_block '^    ApiResponse:' '^    ApiErrorResponse:'
  echo '```'
  echo
  echo "## Error Codes (ErrorCode)"
  echo
  echo '```yaml'
  extract_block '^    ErrorCode:' '^    ApiResponseMeta:'
  echo '```'
  echo
  echo "## Pagination Schemas"
  echo
  echo "### PageResult"
  echo
  echo '```yaml'
  extract_block '^    PageResult:' '^    CursorResult:'
  echo '```'
  echo
  echo "### CursorResult"
  echo
  echo '```yaml'
  extract_block '^    CursorResult:' '^    HealthPayload:'
  echo '```'
  echo
  echo "## Security Schemes (components.securitySchemes)"
  echo
  echo '```yaml'
  extract_block '^  securitySchemes:' '^  schemas:'
  echo '```'
  echo
  echo "## Exception Handling (from x-rules.exceptionHandling)"
  echo
  echo '```yaml'
  extract_block '^  exceptionHandling:' '^  languageImplementations:'
  echo '```'
  echo
  echo "## Language-specific Guidance (from x-rules.languageImplementations)"
  echo
  echo '```yaml'
  extract_block '^  languageImplementations:' '^  httpStatusPolicy:'
  echo '```'
  echo
  echo "## Documentation Workflow (from x-rules.documentation)"
  echo
  echo '```yaml'
  extract_block '^  documentation:' '^  testing:'
  echo '```'
  echo
  echo "## Testing Requirements (from x-rules.testing)"
  echo
  echo '```yaml'
  extract_block '^  testing:' '^  versioning:'
  echo '```'
  echo
  echo "## Versioning and Deprecation (from x-rules.versioning)"
  echo
  echo '```yaml'
  extract_block '^  versioning:' '^  security:'
  echo '```'
  echo
  echo "## Security and Access Control (from x-rules.security)"
  echo
  echo '```yaml'
  extract_block '^  security:' '^  observability:'
  echo '```'
  echo
  echo "## Logging and Monitoring (from x-rules.observability)"
  echo
  echo '```yaml'
  extract_block '^  observability:' '^  developerGuide:'
  echo '```'
  echo
  echo "## Developer Guide (from x-rules.developerGuide)"
  echo
  echo '```yaml'
  extract_block '^  developerGuide:' '^  llmCodingConstraints:'
  echo '```'
  echo
  echo "## LLM Coding Constraints (from x-rules.llmCodingConstraints)"
  echo
  echo '```yaml'
  extract_to_eof '^  llmCodingConstraints:'
  echo '```'
} > "$tmp_file"

mv "$tmp_file" "$HUMAN_FILE"
echo "Synced: $HUMAN_FILE <- $OPENAPI_FILE"
